### ISSUE TITLE
no sms is sending

### ISSUE THREAD

**Issue by tammynm** [technofreaky/cf7-international-sms-intergation#1]
I have installed the plugin "cf7-international-sms-intergation" and set phone number( both admin and user as per instructed ) in contact form 7 as well. Please see attached image. But there are no sms sending when I test it from front end. But I received the email which is the facility of Contact Form 7. 
Is there any thing do I need to do more for SMS?

![no_sms](https://cloud.githubusercontent.com/assets/16397962/11950616/f38c360e-a8c4-11e5-8d21-2366318e9b56.png)

**Comment by varunsridharan** [comment]
@tammynm hi

first you need to configure the sms gateway api. then only it can send the sms

**Comment by tammynm** [comment]
Where and how can I set up sms gateway?

**Comment by varunsridharan** [comment]
first you need to have a sms gateway service.. the you need to configure via admin with the api details

**Comment by tammynm** [comment]
Yes. I have Sms gateway service "clickatell".
Where do I have to configure it in your plugin? Or else do I need another plugin to configure SMs gateway?

**Comment by varunsridharan** [comment]
Ho ok if you need I can configure it for you
It will be chargeable

**Comment by tammynm** [comment]
Can you tell me, Where do I have to configure it in your plugin since I
have clickatell sms gateway service?

**Comment by varunsridharan** [comment]
There will be a settings panel in cf7 menu you can check there

**Comment by tammynm** [comment]
I have sms gateway ... clickatell name, clickatell api, clickatell password
and my phone number.
I saw this as an example in you Setting panel as below. Kindly provoid
below example replaced with my sms gateway information provided above.
Thanks
.
http://example.com/smsAPI/send.php?mobile={MOBILENUMBER}&message={MESSAGE}&senderID=XXX&username=xxx&password=xxx&route=3

**Comment by varunsridharan** [comment]
Hi,

I am sorry i can provide any more support reg setting up the plugin.
if you need you can pay me and get the plugin working :) or you can do it your self

**Comment by tammynm** [comment]
No problem. In that case I will use other plugin.
Thanks

**Comment by varunsridharan** [comment]
Ok thanks for trying out my plugin :)
